# Generated by Django 4.2.5 on 2023-09-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='staffId',
            new_name='staff_id',
        ),
        migrations.AlterModelTable(
            name='guestdata',
            table='hotel_guest_data',
        ),
        migrations.AlterModelTable(
            name='reservationservices',
            table='hotel_reservation_services',
        ),
        migrations.AlterModelTable(
            name='roomdata',
            table='hotel_room_data',
        ),
    ]
