# Generated by Django 4.2.5 on 2023-09-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='created_at',
        ),
    ]
