# Generated by Django 4.2.5 on 2023-09-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_staff_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stafflogin',
            old_name='staff',
            new_name='staffId',
        ),
    ]
