# Generated by Django 4.2.5 on 2023-09-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_rename_guest_room_guest_id_alter_room_room_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='hotel_room',
        ),
    ]
