# Generated by Django 4.2.5 on 2023-09-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_rename_staff_stafflogin_staffid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafflogin',
            name='staffId',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
