# Generated by Django 4.2.5 on 2024-01-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_staffdata'),
        ('hotel', '0004_rename_staff_customstaff'),
    ]

    operations = [
    ]
