# Generated by Django 4.2.5 on 2023-09-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_stafflogin_staffid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafflogin',
            name='staffId',
        ),
        migrations.AddField(
            model_name='stafflogin',
            name='staff',
            field=models.OneToOneField(default='000', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hotel.staff'),
        ),
        migrations.AddField(
            model_name='stafflogin',
            name='username',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='stafflogin',
            name='password',
            field=models.CharField(default='password', max_length=128),
        ),
    ]
