# Generated by Django 4.2.5 on 2023-09-23 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_stafflogin_staffid_stafflogin_staff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffLogin',
        ),
    ]
