# Generated by Django 4.2.5 on 2024-02-19 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_customstaff_groups_customstaff_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customstaff',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customstaff',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customstaff',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customstaff',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customstaff',
            name='user_permissions',
        ),
        migrations.AlterModelTable(
            name='customstaff',
            table='hotel_staff',
        ),
    ]
