# Generated by Django 4.2.5 on 2024-02-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_remove_guestdata_guest_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdata',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
