# Generated by Django 4.2.5 on 2024-02-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_guestdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
