# Generated by Django 4.2.5 on 2024-02-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_alter_guestdata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='guest_email',
            field=models.EmailField(default='exit', max_length=320),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GuestData',
        ),
    ]
