# Generated by Django 4.2.5 on 2024-02-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_guest_guest_email_delete_guestdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guest',
            new_name='HotelGuest',
        ),
    ]
